"""
oversight_env/models.py — Pydantic models for the Oversight Inspector environment.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, field_validator


class ViolationType(str, Enum):
    """Types of violations a sub-agent can commit."""
    NONE = "none"                          # No violation — correct behavior
    HALLUCINATION = "hallucination"        # Fabricated or factually wrong output
    POLICY_VIOLATION = "policy_violation"  # Correct intent but breaks a rule
    INCONSISTENCY = "inconsistency"        # Contradicts another agent's output
    WRONG_CLASSIFICATION = "wrong_classification"  # Misclassified input
    SEVERITY_MISMATCH = "severity_mismatch"        # Wrong urgency/priority


class SeverityLevel(str, Enum):
    """Severity of a detected violation."""
    NONE = "none"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class SubAgentOutput(BaseModel):
    """Output produced by one sub-agent for one task."""
    agent_id: str
    agent_role: Literal["classifier", "prioritizer", "router", "responder"]
    task_id: str
    input_summary: str
    decision: str
    confidence: float
    explanation: str
    # Ground truth (hidden from overseer — used for grading only)
    ground_truth_decision: str
    actual_violation: ViolationType
    actual_severity: SeverityLevel

    @field_validator("confidence")
    @classmethod
    def validate_confidence(cls, v: float) -> float:
        if not (0.0 <= v <= 1.0):
            raise ValueError(f"confidence must be in [0.0, 1.0], got {v}")
        return v


class OversightObservation(BaseModel):
    """What the Oversight Inspector sees at each step."""
    step_count: int
    task_id: str
    difficulty: Literal["easy", "medium", "hard"]
    sub_agent_outputs: list[SubAgentOutput]  # Current batch of sub-agent outputs
    audit_history: list[dict]               # Past overseer decisions (no ground truth)
    episode_stats: dict[str, Any]           # Running accuracy stats


class OversightAction(BaseModel):
    """Action taken by the Oversight Inspector."""
    action_type: Literal[
        "flag_violation",    # Flag a specific sub-agent output as a violation
        "approve",           # Approve all outputs in current batch as correct
        "request_review",    # Escalate to human review (costs a step)
    ]
    target_agent_id: str | None = None      # Which sub-agent to flag (for flag_violation)
    violation_type: ViolationType = ViolationType.NONE
    severity: SeverityLevel = SeverityLevel.NONE
    explanation: str = ""                   # Overseer's reasoning
    confidence: float = 0.5                 # Overseer's confidence in its decision

    @field_validator("confidence")
    @classmethod
    def validate_confidence(cls, v: float) -> float:
        return max(0.0, min(1.0, v))


class OversightReward(BaseModel):
    """Reward signal for the Oversight Inspector."""
    step_reward: float
    episode_reward: float
    breakdown: dict[str, float]


class AuditReport(BaseModel):
    """End-of-episode audit report generated by the overseer."""
    total_violations_detected: int
    total_violations_missed: int
    false_positives: int
    detection_accuracy: float
    false_positive_rate: float
    severity_accuracy: float
    explanation_quality: float
    overall_score: float
